# Generated by Django 5.1.2 on 2024-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('isin', models.CharField(max_length=48)),
                ('type', models.CharField(choices=[('EQ', 'equity'), ('SEC', 'security'), ('FX', 'forex'), ('CASH', 'cash')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('last_obbserved_price', models.FloatField()),
                ('volatility', models.FloatField()),
                ('oneyear_roi', models.FloatField()),
            ],
        ),
    ]
